name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend dependencies
        working-directory: ./crew-builder-v2/frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./crew-builder-v2/backend
        run: npm install

      - name: Run backend tests
        working-directory: ./crew-builder-v2/backend
        run: npm test
